# Generated by Django 4.2 on 2023-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, unique=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PostProduct',
        ),
    ]
